#!/bin/bash
set -e
/usr/bin/env jazzy \
  --author Weebly \
  --author_url https://weebly.com \
  --github_url https://github.com/Weebly/FunKit \
  --github-file-prefix https://github.com/Weebly/FunKit/tree/v0.1.0 \
  --module-version 0.1.0 \
  --xcodebuild-arguments -scheme,FunKit \
  --module FunKit \
  --root-url https://weebly.github.io/FunKit/ \
  --output ../FunKit-docs

#  --use-safe-filenames
#  --clean \
#  --theme docs/themes
